spring:
  application:
    name: spring-batch-work
  jpa:
    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: aa
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'